import type { ServiceEntry } from "../config.ts";

export type ProviderCategory =
  | "database"
  | "deploy"
  | "cloud"
  | "analytics"
  | "observability"
  | "errors"
  | "ai"
  | "payments"
  | "code"
  | "tickets"
  | "email"
  | "auth"
  | "featureflags"
  | "comms";

export type AuthKind = "oauth_pkce" | "oauth_device" | "pat" | "api_key" | "cli_shell";

export interface ProviderContext {
  cwd: string;
  /** If non-interactive (CI, agent), providers should fail fast instead of prompting. */
  interactive: boolean;
  /** Structured logger — callers wire this to the CLI's @clack spinner. */
  log: (event: LogEvent) => void;
  /**
   * Provider-specific hints forwarded from the CLI (e.g. webhookEndpoint,
   * secretKeyFromVault). Available to both `login` and `provision` so providers
   * can alter their auth flow based on flags.
   */
  hints?: Record<string, unknown>;
  /**
   * Abort signal tied to the pipeline's wall-clock timeout. Providers MAY
   * thread this into fetch() calls or polling loops to self-cancel early.
   * Back-compat: providers that ignore it still get the wall-clock cutoff.
   */
  signal?: AbortSignal;
}

export interface LogEvent {
  level: "info" | "warn" | "error";
  msg: string;
  data?: Record<string, unknown>;
}

export interface AuthHandle {
  /** Opaque, provider-specific. Usually an access token or PAT. */
  token: string;
  /** Optional provider-side identity (user id, email, org id). */
  identity?: Record<string, string>;
  /** Epoch ms when token expires. Omit if non-expiring. */
  expiresAt?: number;
}

export interface ProvisionOpts {
  /** If the user already has a resource on the provider side, use this instead of creating. */
  existingResourceId?: string;
  /** Provider-specific provisioning hints (region, tier, org). */
  hints?: Record<string, unknown>;
}

export interface Resource {
  id: string;
  displayName: string;
  region?: string;
  /** Provider-specific fields persisted into .stack.toml meta. */
  meta?: Record<string, unknown>;
}

export interface Materialized {
  /** Secrets to store in Phantom vault. Key is the .env name, value is the real secret. */
  secrets: Record<string, string>;
  /** Optional MCP server entry to merge into .mcp.json. */
  mcp?: McpServerEntry;
  /** Environment URLs or hints to expose in `stack status`. */
  urls?: Record<string, string>;
}

export interface McpServerEntry {
  name: string;
  type?: "stdio" | "sse" | "http";
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  headers?: Record<string, string>;
}

export type HealthStatus =
  | { kind: "ok"; latencyMs?: number; detail?: string }
  | { kind: "warn"; detail: string }
  | { kind: "error"; detail: string };

/**
 * Extended health status that includes quota and rate-limit telemetry.
 * Providers that support quota/rate-limit headers (GitHub, OpenAI, Anthropic,
 * etc.) should populate these fields from response headers.
 *
 * quotaUsedPercent  — 0–100, derived from x-ratelimit-used / x-ratelimit-limit
 *                     or equivalent provider-specific headers.
 * rateLimitRemaining — raw remaining-requests value from response headers.
 * estimatedBurnRatePerDay — human-readable estimate, e.g. "1200 req/day".
 */
export interface HealthStatusMetrics {
  quotaUsedPercent?: number;
  rateLimitRemaining?: number;
  estimatedBurnRatePerDay?: string;
}

export type HealthStatusWithMetrics = HealthStatus & HealthStatusMetrics;

// ---------------------------------------------------------------------------
// Resource conflict detection
// ---------------------------------------------------------------------------

/**
 * Configuration for how a provider checks resource name collisions before
 * calling `provision()`. Returned by `Provider.checkConflict()`.
 */
export interface ResourceConflictCheckConfig {
  /**
   * The resource name / slug / org that was requested (what the caller
   * intended to create).
   */
  requestedName: string;
  /**
   * Whether a resource with this name already exists on the provider side.
   * `undefined` means the check could not be performed (e.g. provider unreachable).
   */
  exists: boolean | undefined;
  /**
   * If `exists` is true, the upstream resource id of the existing resource.
   * Can be passed as `existingResourceId` in ProvisionOpts to attach instead.
   */
  existingResourceId?: string;
  /**
   * If `exists` is true, the human-readable display name of the existing resource.
   */
  existingDisplayName?: string;
  /**
   * A unique name that is guaranteed not to collide, generated by the provider
   * by appending a timestamp suffix. Only populated when `exists` is true.
   */
  suggestedUniqueName?: string;
  /**
   * The action that was taken / recommended:
   *   - "attach"   — caller should re-issue provision() with existingResourceId
   *   - "rename"   — caller should re-issue provision() with the suggestedUniqueName
   *   - "fail"     — caller should surface the conflict to the user and stop
   *   - "ok"       — no conflict; proceed normally
   *   - "skipped"  — check was not attempted (dry-run, CI with flag=false, etc.)
   *   - "unreachable" — provider API was unreachable; check skipped (non-blocking)
   */
  action: "attach" | "rename" | "fail" | "ok" | "skipped" | "unreachable";
  /** Human-readable message explaining the outcome. */
  message: string;
  /** ISO timestamp of when the check was performed. */
  checkedAt: string;
}

/**
 * Options for `Provider.checkConflict()`.
 */
export interface ConflictCheckOpts {
  /**
   * The desired resource name. Providers use their own slug/naming conventions.
   * When omitted the provider falls back to an auto-generated name.
   */
  desiredName?: string;
  /**
   * Provider-specific hints forwarded from the CLI (e.g. orgId, region).
   */
  hints?: Record<string, unknown>;
  /**
   * AbortSignal tied to the pipeline's wall-clock timeout.
   */
  signal?: AbortSignal;
}

export interface Provider {
  name: string;
  displayName: string;
  category: ProviderCategory;
  authKind: AuthKind;
  /** Human-readable docs URL for when something goes wrong. */
  docs?: string;

  /**
   * Semver string for the provider's `provisionResponseSchema` definition.
   * e.g. "1.0.0". Increment this when the schema changes to allow cache
   * invalidation and `stack validate-schema` version-drift detection.
   *
   * Optional — defaults to "1.0.0" when not declared.
   */
  schemaVersion?: string;

  /**
   * OpenAPI 3.1–compatible JSON Schema fragment describing the expected shape
   * of the raw object returned by `provision()`. When declared here the pipeline
   * auto-registers it via `registerProviderSchema()` at startup and the
   * `SchemaValidator` uses it to validate every provision response before
   * persisting to `.stack.toml` or Phantom.
   *
   * The schema must be a `JsonSchemaProperty` with `type: "object"`.
   * Required fields must map to at least `id` and `displayName` (or their
   * provider-specific equivalents as declared in the `mapping` block).
   *
   * Optional — if omitted the provider falls back to the built-in schema
   * registered in `provision-schema.ts` (if any), or passes through without
   * validation in non-strict mode.
   */
  provisionResponseSchema?: import("../provision-schema.ts").ProvisionResponseSchemaWithVersion;

  login(ctx: ProviderContext): Promise<AuthHandle>;
  provision(ctx: ProviderContext, auth: AuthHandle, opts: ProvisionOpts): Promise<Resource>;
  materialize(ctx: ProviderContext, resource: Resource, auth: AuthHandle): Promise<Materialized>;

  healthcheck?(ctx: ProviderContext, entry: ServiceEntry): Promise<HealthStatusWithMetrics>;
  dashboardUrl?(entry: ServiceEntry): string;

  /**
   * Tear down an upstream resource created by `provision`. Used by `addService`
   * to roll back on partial failure. Optional — if the provider doesn't
   * implement it, the dangling resource is logged and the user is directed to
   * `stack doctor --fix`.
   */
  deprovision?(ctx: ProviderContext, auth: AuthHandle, resourceId: string): Promise<void>;

  /**
   * Check whether a resource with the requested name already exists on the
   * provider side, BEFORE calling `provision()`.
   *
   * Implementations should call the provider's list/get endpoint and compare
   * names. If the check fails (network error, auth failure), they MUST return
   * `action: "unreachable"` — a failed check must never block provisioning.
   *
   * Optional — providers that do not implement it behave as if they returned
   * `{ exists: undefined, action: "skipped" }`.
   */
  checkConflict?(
    auth: AuthHandle,
    opts: ConflictCheckOpts,
  ): Promise<ResourceConflictCheckConfig>;

  /**
   * Validate that the credentials described by `auth` are scoped to least-
   * privilege. Implementations introspect the actual granted scopes (via API
   * calls or token inspection) and compare them to the provider's PermissionSet.
   *
   * Returns a structured result with status, violations, and optional
   * remediation instructions. Must never throw — return status "error" instead.
   *
   * Optional — providers without an implementation are reported as "skipped"
   * by the permission-validator engine.
   */
  validatePermissions?(
    ctx: ProviderContext,
    auth: AuthHandle,
    opts?: { fix?: boolean; signal?: AbortSignal },
  ): Promise<import("../permission-validator.ts").PermissionValidationResult>;
}
