/**
 * Recipe → Phantom envelope + webhook stub materializer.
 *
 * For each provider in a Recipe:
 *   1. Pre-create Phantom envelopes (one per declared secret) so `stack add`
 *      slots its real values into an already-rotating slot.
 *   2. For webhook-capable providers (Stripe, Clerk, Supabase, GitHub),
 *      scaffold a commented-out handler stub in `.stack/webhooks/<provider>.ts`
 *      so the user has somewhere concrete to land the signature verification.
 *
 * This is the Stack moat: `stack apply` ends with envelopes + stubs waiting
 * for the real credentials, which the provider-specific `addCommand` flow
 * then fills in. An opt-out (`--no-wire`) exists for users who want pure
 * provisioning without Phantom-assisted rotation.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { findProviderRef } from "../catalog.ts";
import { PhantomNotInstalledError } from "../errors.ts";
import { type PhantomExecResult, assertPhantomInstalled, exec as phantomExec } from "../phantom.ts";
import type { Recipe } from "./recipe.ts";

export interface WireResult {
  /** `PROVIDER:SECRET_NAME` entries successfully added to Phantom. */
  envelopes: string[];
  /** Absolute paths of webhook stub files created. */
  webhooks: string[];
  /** Names of providers skipped (phantom missing, unknown provider, etc). */
  skipped: string[];
}

const PLACEHOLDER = "TODO_STACK_APPLY";

/**
 * Providers with webhooks worth pre-wiring. Keep this list tight — each entry
 * gets a hand-maintained stub in `webhookStubFor`. Adding a new provider here
 * without also adding its stub produces an empty file, which is worse than
 * no file.
 */
const WEBHOOK_PROVIDERS = new Set(["stripe", "clerk", "supabase", "github"]);

export async function wirePhantomForRecipe(
  recipe: Recipe,
  opts: { cwd?: string; noWire?: boolean } = {},
): Promise<WireResult> {
  const result: WireResult = { envelopes: [], webhooks: [], skipped: [] };
  if (opts.noWire) return result;

  const cwd = opts.cwd ?? process.cwd();

  try {
    await assertPhantomInstalled();
  } catch (err) {
    if (err instanceof PhantomNotInstalledError) {
      // Phantom missing → skip envelope creation but still drop webhook stubs
      // (they're just files). Surface the provider names so the CLI can tell
      // the user why nothing landed in the vault.
      for (const p of recipe.providers) result.skipped.push(p.name);
      for (const p of recipe.providers) {
        if (WEBHOOK_PROVIDERS.has(p.name)) {
          const path = await writeWebhookStub(cwd, p.name);
          result.webhooks.push(path);
        }
      }
      return result;
    }
    throw err;
  }

  for (const { name } of recipe.providers) {
    const ref = findProviderRef(name);
    if (!ref) {
      result.skipped.push(name);
      continue;
    }

    for (const secret of ref.secrets) {
      const added = await addEnvelope(secret, cwd);
      if (added) result.envelopes.push(`${name}:${secret}`);
    }

    if (WEBHOOK_PROVIDERS.has(name)) {
      const path = await writeWebhookStub(cwd, name);
      result.webhooks.push(path);
    }
  }

  return result;
}

/**
 * Shell `phantom add <KEY> <placeholder>` with opportunistic `--rotate`.
 * Try with `--rotate` first; if the running Phantom doesn't support the flag,
 * fall back to a flagless add. Returns true when the envelope was written.
 */
async function addEnvelope(key: string, cwd: string): Promise<boolean> {
  const rotateAttempt = await tryExec(["add", key, PLACEHOLDER, "--rotate"], cwd);
  if (rotateAttempt.code === 0) return true;

  // Heuristic for "Phantom rejected --rotate because it's an older build":
  // stderr mentions the flag name or "unknown option". On any other failure,
  // we already logged it via stderr — the caller's noWire path can skip.
  const stderrLower = rotateAttempt.stderr.toLowerCase();
  const looksLikeUnknownFlag =
    stderrLower.includes("--rotate") ||
    stderrLower.includes("unknown option") ||
    stderrLower.includes("unrecognized");

  if (!looksLikeUnknownFlag) return false;

  const fallback = await tryExec(["add", key, PLACEHOLDER], cwd);
  return fallback.code === 0;
}

async function tryExec(args: string[], cwd: string): Promise<PhantomExecResult> {
  try {
    return await phantomExec(args, { cwd, allowFailure: true });
  } catch {
    return { stdout: "", stderr: "", code: 1 };
  }
}

async function writeWebhookStub(cwd: string, provider: string): Promise<string> {
  const path = resolve(cwd, ".stack", "webhooks", `${provider}.ts`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, webhookStubFor(provider), "utf-8");
  return path;
}

function webhookStubFor(provider: string): string {
  const base = `// Auto-generated by \`stack apply\` — webhook handler stub for ${provider}.
// Fill in the secret retrieval + signature verification before deploying.
//
// Secret envelope lives in Phantom; read it at call time with:
//   phantom reveal ${webhookSecretKeyFor(provider)}
//
// export async function handle${capitalize(provider)}Webhook(req: Request): Promise<Response> {
//   const signature = req.headers.get("${signatureHeaderFor(provider)}");
//   const body = await req.text();
//   // TODO: verify(signature, body) before trusting.
//   return new Response("ok", { status: 200 });
// }
`;
  return base;
}

function webhookSecretKeyFor(provider: string): string {
  switch (provider) {
    case "stripe":
      return "STRIPE_WEBHOOK_SECRET";
    case "clerk":
      return "CLERK_WEBHOOK_SECRET";
    case "supabase":
      return "SUPABASE_WEBHOOK_SECRET";
    case "github":
      return "GITHUB_WEBHOOK_SECRET";
    default:
      return `${provider.toUpperCase()}_WEBHOOK_SECRET`;
  }
}

function signatureHeaderFor(provider: string): string {
  switch (provider) {
    case "stripe":
      return "stripe-signature";
    case "clerk":
      return "svix-signature";
    case "supabase":
      return "x-supabase-signature";
    case "github":
      return "x-hub-signature-256";
    default:
      return "x-webhook-signature";
  }
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
